version: '3.8'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}  # From .env
    volumes:
      - ./:/app       # Live reload (remove in production)
      - /app/node_modules  # Avoid host node_modules override